###Resgistro 1
POST http://localhost:3000/api/clients/register HTTP/1.1a
Content-Type: application/json

{
    "name": "Juan Perez",
    "email": "juan.perez@example.com",
    "password": "password123",
    "age": "30",
    "city": "Lima",
    "interests": ["turismo", "lectura", "viajes"],
    "spam": true
}

###Resgistro 2
POST http://localhost:3000/api/clients/register HTTP/1.1
Content-Type: application/json

{
    "name": "Ana López",
    "email": "ana.lopez@example.com",
    "password": "password456",
    "age": "28",
    "city": "Arequipa",
    "interests": ["fotografía", "cocina", "yoga"],
    "spam": false
}

###Login 1
POST http://localhost:3000/api/clients/login HTTP/1.1
Content-Type: application/json

{
    "email": "juan.perez@example.com",
    "password": "password123"
}

###Login 2
POST http://localhost:3000/api/clients/login HTTP/1.1
Content-Type: application/json

{
    "email": "ana.lopez@example.com",
    "password": "password456"
}

###Actualizar usuario 1
PUT http://localhost:3000/api/clients/update/673bc5b4d4e8da059529bbd2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzNiYzViNGQ0ZThkYTA1OTUyOWJiZDIiLCJyb2xlIjpbImNsaWVudCJdLCJpYXQiOjE3MzE5NzA2NjIsImV4cCI6MTczMTk4NTA2Mn0.8veW0I8xOqM_07cer6Az8hJpyTWhvPX2tjMjQuuomGk

{
    "name": "Juan Tetas",
    "email": "juan.tetas@example.com",
    "password": "wheneresgei",
    "age": "32",
    "city": "Puen",
    "interests": ["Anime", "limpiar", "pelear"],
    "spam": false
}

###Borrar Usuario
DELETE http://localhost:3000/api/clients/delete/6743103fddd3fdd3d0dec724
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQzMTAzZmRkZDNmZGQzZDBkZWM3MjQiLCJyb2xlIjpbImNsaWVudCJdLCJpYXQiOjE3MzI0NDgzMjEsImV4cCI6MTczMjQ2MjcyMX0.FsbzFsZjNSExU9qWVf7zNR6VfFDq_8j3E_e5vJTbEAM