
#Mostrar todas las webs
GET http://localhost:3000/api/web HTTP/1.1

###
#Peticion por id
GET http://localhost:3000/api/web/672292db0bab811cf14b8c9e HTTP/1.1
###
Get http://localhost:3000/api/web/clients/turismo




#Crear un nueva web
POST http://localhost:3000/api/web HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MzAzMTg1MzEsImV4cCI6MTc2MTg1NDUzMX0.kL13WcMk4Z-8hSf_TiLQkNLWWhHtPEYznlnzzDFMHVA

{
  "city": "Lima",
  "activity": "Turismo",
  "tittle": "Explorando Lima",
  "sumary": "Una guía rápida para conocer Lima",
  "text": ["Texto del artículo sobre Lima"],
  "img": [],
  "client_review": {
    "scoring": 4,
    "score": 5,
    "reviews": "Muy buen artículo"
  }
}


###
#Actualizar datos de una web
PUT http://localhost:3000/api/web/672290d2e6664c34a712a7e9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJCOTg3NjU0MzIiLCJpYXQiOjE3MzAzMTk0MzksImV4cCI6MTc2MTg1NTQzOX0.qLrCF9dyDXPRNj2L8dLvWhsUTLdFWzOmH6nCaM9vSdY

{
  "city": "Cerru",
  "activity": "Turismo",
  "tittle": "Explorando Lima",
  "sumary": "Una guía rápida para conocer Lima",
  "text": ["Texto del artículo sobre Lima"],
  "img": [],
  "client_review": {
    "scoring": 4,
    "score": 5,
    "reviews": "Muy buen artículo"
  }
}

###
PATCH http://localhost:3000/api/web/text/672292db0bab811cf14b8c9e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MzAzMjA1ODcsImV4cCI6MTc2MTg1NjU4N30.9EyrpxiAlx4L_eOua_qby3WmgsNEPxF9H4NooH9G-ao

{
  "text": ["Nuevo tsexto del artículo sobre Lima"]
}

###
PATCH http://localhost:3000/api/web/img/672292db0bab811cf14b8c9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MzAzMjA1ODcsImV4cCI6MTc2MTg1NjU4N30.9EyrpxiAlx4L_eOua_qby3WmgsNEPxF9H4NooH9G-ao
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./amogus.jpg
--Boundry--

###
#Borrado fisico
DELETE http://localhost:3000/api/web/672290d2e6664c34a712a7e9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MzAzMTg1MzEsImV4cCI6MTc2MTg1NDUzMX0.kL13WcMk4Z-8hSf_TiLQkNLWWhHtPEYznlnzzDFMHVA

###
#Borrado logico
DELETE http://localhost:3000/api/web/archive/672290d2e6664c34a712a7e9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MzAzMTg1MzEsImV4cCI6MTc2MTg1NDUzMX0.kL13WcMk4Z-8hSf_TiLQkNLWWhHtPEYznlnzzDFMHVA
